version: "3.9"

services:
  backend:
    build: ./backend
    container_name: course-backend
    ports:
      - "8080:8080"
    networks:
      - course-network

  frontend:
    build: ./frontend
    container_name: course-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - course-network

networks:
  course-network:
    driver: bridge
